# Generated by Django 2.0.2 on 2018-04-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrdersApp.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='Products',
            field=models.ManyToManyField(to='OrdersApp.OrderItem'),
        ),
    ]
