# Generated by Django 2.0.3 on 2018-03-17 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='PaymentMethod',
            field=models.CharField(choices=[(0, 'Credit Card'), (1, 'From Wallet'), (2, 'On Pickup')], default=2, max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='PickupTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
