# Generated by Django 2.0.3 on 2018-04-29 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrdersApp.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='PhoneNumber',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='Products',
            field=models.ManyToManyField(to='OrdersApp.OrderItem'),
        ),
    ]
