# Generated by Django 2.0.3 on 2018-04-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='Wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='PhoneNumber',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='PaymentMethod',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('From Wallet', 'From Wallet'), ('On Pickup', 'On Pickup')], default=2, max_length=100),
        ),
    ]
