# Generated by Django 2.0.2 on 2018-05-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0002_auto_20180429_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='PhoneNumber',
        ),
    ]
