# Generated by Django 2.0.3 on 2018-03-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0002_auto_20180317_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='PickupTime',
            field=models.DateField(verbose_name='pickup date'),
        ),
    ]
