# Generated by Django 2.0.3 on 2018-04-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, default='products_images/no-img.jpg', null=True, upload_to='products_images'),
        ),
    ]
