# Generated by Django 2.0.2 on 2018-05-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0003_remove_customerprofile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='PhoneNumber',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
