# Generated by Django 2.0.3 on 2018-03-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0003_auto_20180317_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='PickupTime',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
