# Generated by Django 2.0.3 on 2018-05-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0004_auto_20180429_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, default='OrdersApp/static/products_images/no-img.jpg', null=True, upload_to='OrdersApp/static/products_images'),
        ),
    ]
