# Generated by Django 2.0.3 on 2018-03-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0004_auto_20180317_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='PaymentMethod',
            field=models.CharField(choices=[('credit', 'Credit Card'), ('wallet', 'From Wallet'), ('cash', 'On Pickup')], default=2, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='PickupTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
