# Generated by Django 2.0.3 on 2018-05-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0005_auto_20180505_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, default='products_images/no-img.jpg', null=True, upload_to='products_images'),
        ),
    ]
