# Generated by Django 2.0.3 on 2018-05-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0006_auto_20180505_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='PaymentMethod',
            field=models.CharField(choices=[('CreditCard', 'Credit Card'), ('Wallet', 'From Wallet'), ('OnPickup', 'On Pickup')], default=2, max_length=100),
        ),
    ]
