# Generated by Django 2.0.3 on 2018-05-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0008_auto_20180505_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='OrdersApp.Product'),
        ),
    ]
